name: Test Automatic Build
on:
  release:
    types: [ published ]

jobs:
  automatic-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
