name: Static Code Analysis
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Brakeman analysis
        uses: ./.github/actions/brakeman-action
        with:
          args: "--color"
